settings:
  default-group: Default
  always-inherit-default-group: false
  treat-asterisk-as-op: true
  auto-reload-delay-sec: 900
  use-metrics: true
  language: english
  maintenance-mode: ''
  region-finder-thread-granularity-msec: 1000
  integration:
    worldguard: true
    residence: true
servers:
- nodename: db-primary-remote
  database: localhost:3306/minecraft
  username: user1
  password: pass1
  prefixes: rscp_
  workmode: fullaccess
- nodename: db-secondary-local-replication
  database: other.server:3306/replication
  username: user2
  password: pass2
  prefixes: rscp_
  workmode: none
internal:
  version: 1
