settings:
  default-group: Default
  always-inherit-default-group: true
  treat-asterisk-as-op: true
  auto-reload-delay-sec: 900
  region-finder-thread-granularity-msec: 1000
  integration:
    worldguard: true
    residence: true
  use-metrics: true
  connection:
    database: localhost:3306/minecraft
    username: user1
    password: pass1
    prefixes: rscp_
  slot-limits:
    administrators: 5
    premium: 25
  maintenance-mode: ''
  language: english
internal:
  version: 3
