settings:
  default-group: Default
  always-inherit-default-group: false
  treat-asterisk-as-op: true
  auto-reload-delay-sec: 900
  use-metrics: true
  language: en_US
  maintenance-mode: ''
  region-finder-thread-granularity-msec: 1000
  integration:
    worldguard: true
    residence: true
servers:
- nodename: db-primary-remote
  database: localhost:3306/minecraft
  username: user1
  password: pass1
  prefixes: rscp_
  workmode: fullaccess
- nodename: db-secondary-local-replication
  database: other.server:3306/replication
  username: user2
  password: pass2
  prefixes: rscp_
  workmode: none
language:
  maintenance:
    unlocked: '{_YL}Server left the maintenance mode'
    locked:
      default:
        mmon: '{_YL}Server is going into maintenance mode.{_NL}{_YL}All players without permissions will be kicked.'
        kick: '{_YL}Server is in maintenance mode\nPlease try to connect later...'
        motd: '{_DR}Server is under maintenance'
      rollback:
        motd: '{_DR}Rolling back griefing.'
      worldedit:
        motd: '{_DR}We are editing world with WE.'
internal:
  version: 1
