name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.MainPluginClass
author: SimSonic
website: http://dev.bukkit.org/server-mods/rscPermissions
softdepend:
  - Vault
  - WorldEdit
  - WorldGuard
  - Residence
commands:
  rscp:
    description: rscPermissions command hub
  promote:
    description: Promotes player on ladder
  demote:
    description: Demotes player on ladder
permissions:
  rscp.*:
    description: Gives access to all commands
    default: op
    children:
      rscp.admin: true
  rscp.admin:
    description: Allows you to use all /rscp subcommands
    default: op
    children:
      rscp.admin.promote: true
      rscp.admin.lock: true
      rscp.admin.reload: true
      rscp.maintenance.*: true
  rscp.admin.promote:
    description: Allows to promote/demote users on ladders
    default: op
  rscp.admin.lock:
    description: Allows to enable/disable maintenance modes
    default: op
  rscp.admin.reload:
    description: Allows to reload configuration and database
    default: op
  rscp.maintenance.*:
    description: Allows to connect when server in any maintenance mode
    default: op
